// Auto-generated by OpenLane
module synth_top(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input rst_n,
  input[7:0] x0,
  input[7:0] x1,
  input[7:0] x2,
  input[7:0] x3,
  input[7:0] w00,
  input[7:0] w01,
  input[7:0] w02,
  input[7:0] w03,
  input[7:0] w10,
  input[7:0] w11,
  input[7:0] w12,
  input[7:0] w13,
  input[7:0] w20,
  input[7:0] w21,
  input[7:0] w22,
  input[7:0] w23,
  input[7:0] w30,
  input[7:0] w31,
  input[7:0] w32,
  input[7:0] w33,
  output[16:0] y0,
  output[16:0] y1,
  output[16:0] y2,
  output[16:0] y3
);
endmodule
