SIM = icarus
TOPLEVEL_LANG = verilog
VERILOG_SOURCES = $(PWD)/mac_correct.v
TOPLEVEL = mac
MODULE = test_mac
COCOTB_HDL_TIMEUNIT = 1ns
COCOTB_HDL_TIMEPRECISION = 1ps
WAVES = 1
include $(shell cocotb-config --makefiles)/Makefile.sim
